<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Serialize.Linq" Version="4.0.167" />
    <PackageReference Include="Polly" Version="8.6.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <Protobuf Include="./Controllers/generic.proto" GrpcServices="Both" />
  </ItemGroup>

</Project>
